# Generated by Django 3.2 on 2021-05-04 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectCode', models.CharField(max_length=10)),
                ('ProjectName', models.CharField(max_length=50)),
                ('ClientName', models.CharField(max_length=50)),
                ('StartDate', models.DateField(blank=True, default=datetime.date(2021, 5, 4))),
                ('TargetDate', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Active', 'Active')], max_length=10, null=True)),
            ],
        ),
    ]
