# Generated by Django 3.2.1 on 2021-05-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Email',
            new_name='email',
        ),
    ]
