# Generated by Django 3.2.1 on 2021-05-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210507_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Password',
        ),
    ]
