# Generated by Django 3.1.1 on 2021-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Task_title', models.CharField(max_length=50, null=True)),
                ('Task_img', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=70, null=True)),
                ('description_img', models.ImageField(upload_to='images/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
