# Generated by Django 3.1.7 on 2021-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stunamme',
            new_name='stuname',
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(default='not available', max_length=70),
        ),
    ]
 