# Generated by Django 3.1.7 on 2021-05-12 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectCode', models.CharField(max_length=100, null=True)),
                ('ProjectName', models.CharField(max_length=1000, null=True)),
                ('ClientName', models.CharField(max_length=500, null=True)),
                ('StartDate', models.DateTimeField(null=True)),
                ('TargetDate', models.DateTimeField(null=True)),
                ('BA', models.CharField(max_length=500, null=True)),
                ('Department', models.CharField(max_length=200, null=True)),
                ('ProjectHead', models.CharField(max_length=200, null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Active', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('CreatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectcreatedby', to=settings.AUTH_USER_MODEL)),
                ('UpdatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectupdatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
