# Generated by Django 3.2 on 2021-05-04 08:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=datetime.date(2021, 5, 4))),
                ('Day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=2, max_length=10)),
                ('WeekNo', models.IntegerField(default=18)),
                ('Task', models.CharField(max_length=200)),
                ('Status', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Active', 'Active')], max_length=10, null=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
                ('Employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpressModeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField(default=2021)),
                ('WeekNo', models.IntegerField(default=18)),
                ('ExpProjectName', models.CharField(max_length=50)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
                ('Employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
