# Generated by Django 3.2.1 on 2021-05-11 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPriorityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriorityName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TaskNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotificationTitle', models.CharField(max_length=50)),
                ('NotificationMsg', models.CharField(max_length=500, null=True)),
                ('ReadMsg', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('NotificationTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.notificationtypemaster')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('Week', models.IntegerField(default=19, null=True)),
                ('TaskTitle', models.CharField(max_length=50)),
                ('TaskDescription', models.CharField(max_length=500, null=True)),
                ('DueDateTime', models.DateField(null=True)),
                ('Active', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('AssignBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignby', to=settings.AUTH_USER_MODEL)),
                ('AssignTo', models.ManyToManyField(blank=True, related_name='assignto', to=settings.AUTH_USER_MODEL)),
                ('CreatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdby', to=settings.AUTH_USER_MODEL)),
                ('Status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.status')),
                ('TaskPriority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.taskprioritymaster')),
                ('UpdatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
